#!/usr/bin/env sh
# usage: rg --pre to_text ...

case "$1" in
	*.pdf)
		if [ -s "$1" ]; then
			exec pdftotext "$1" -
		else
			exec cat
		fi
		;;
	*.docx|*.odt|*.epub|*.ipynb)
		exec pandoc "$1" -t markdown -o -
		;;
	*.sqlite|*.db)
		exec sqlite "$1" .dump
		;;
	*.sqlite3|*.db3)
		exec sqlite3 "$1" .dump
		;;
	*.tar)
		exec tar xf "$1" -O
		;;
	*.tar.gz|*.tgz)
		exec tar xzf "$1" -O
		;;
	*.tar.bz2|*.tbz2)
		exec tar xjf "$1" -O
		;;
	*.tar.xz|*.txz)
		exec tar xJf "$1" -O
		;;
	*.tar.zst|*.tzst)
		exec tar xf --zstd "$1" -O
		;;
	*.gz)
		exec gunzip -c "$1"
		;;
	*)
		case $(file "$1") in
			*Zstandard*)
				exec pzstd -cdq
				;;
			*)
				exec cat
				;;
		esac
		;;
esac
